//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckWord.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckWord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 最佳
        ///最具
        ///最爱
        ///最赚
        ///最优
        ///最优秀
        ///最好
        ///最大程度
        ///最大
        ///最高级
        ///最高端
        ///最高
        ///最奢侈
        ///最多
        ///最低级
        ///最低价
        ///最底
        ///最便宜
        ///史上最低价
        ///最低
        ///最流行
        ///最受欢迎
        ///最时尚
        ///最聚拢
        ///最符合
        ///最舒适
        ///最先
        ///最先进
        ///最先进科学
        ///最后
        ///最新
        ///最新技术
        ///最新科学
        ///最
        ///中国第一
        ///全网第一
        ///全新
        ///销量第一
        ///排名第一
        ///唯一
        ///第一品牌
        ///NO.1
        ///TOP1
        ///独一无二
        ///全国第一
        ///一流
        ///一天
        ///仅此一次
        ///仅此一款
        ///最后一波
        ///全国
        ///大品牌
        ///之一
        ///第一
        ///销冠
        ///国家级
        ///国际级
        ///世界级
        ///千万级
        ///百万级
        ///星级
        ///5A
        ///甲级
        ///超甲级
        ///顶级
        ///顶尖
        ///尖端
        ///顶级享受
        ///高级
        ///极品
        ///极佳
        ///绝佳
        ///绝对
        ///终极
        ///极致
        ///致极
        ///极具
        ///完美
        ///绝佳
        ///极佳
        ///至尊
        ///至臻
        ///臻品
        ///臻致
        ///臻席
        ///压轴
        ///问鼎
        ///空前
        ///绝后
        ///绝版
        ///无双
        ///非此莫属
        ///巅峰
        ///前所未有
        ///无人能及
        ///顶级
        ///鼎级
        ///鼎冠
        ///定鼎
        ///完美
        ///翘楚之作
        ///不可再生
        ///不可复制
        ///绝无仅有
        ///寸土寸金
        ///淋漓尽致
        ///无与伦比
        ///唯一
        ///卓 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
