//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckWord.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckWord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 最赚
        ///最优秀
        ///最优
        ///最新科学
        ///最新技术
        ///最新
        ///最小
        ///最先进
        ///最科学
        ///最先
        ///最舒适
        ///最受欢迎
        ///最时尚
        ///最奢侈
        ///最牛
        ///最流行
        ///最聚拢
        ///最具
        ///最佳
        ///最后一波
        ///最后
        ///最好
        ///最高级
        ///最高端
        ///最高
        ///最符合
        ///最多
        ///最底
        ///最低价
        ///最低级
        ///最低
        ///最大程度
        ///最大
        ///最便宜
        ///最爱
        ///最
        ///祖传
        ///卓著
        ///卓越
        ///专家推荐
        ///专供
        ///著名
        ///周年庆
        ///周末
        ///重心
        ///重点
        ///众筹
        ///终极
        ///中央
        ///中心
        ///中枢
        ///中国第一
        ///致极
        ///至尊
        ///至尊
        ///至臻
        ///咫尺
        ///直达家门口
        ///之一
        ///之王
        ///政府机关
        ///臻致
        ///臻席
        ///臻稀
        ///臻品
        ///珍稀
        ///掌门人
        ///再不抢就没了
        ///优先入学
        ///永久
        ///隐贵
        ///引领
        ///医院
        ///一站式教育
        ///一天
        ///一流
        ///耀领
        ///压轴
        ///学校名称
        ///学校
        ///星级
        ///销量第一
        ///销冠
        ///限时
        ///稀世珍宝
        ///稀少
        ///无与伦比
        ///无双
        ///无人能及
        ///我在你心
        ///问鼎
        ///位业主
        ///未曾有过的
        ///唯一
        ///唯一
        ///王者楼王
        ///王牌
        ///王府
        ///王
        ///万人疯抢
        ///万能
        ///万亩公园
        ///万达在旁
        ///完美
        ///完美
        ///外国货币
        ///投资回报
        ///填补国内空白
        ///天人合一
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
